all:
	gcc -Wall -Wextra -Werror main.c checker.c check_args.c init_a_b_stacks.c get_next_line.c do_oper.c do_p.c do_r.c do_rr.c do_s.c atoli.c print_stack.c -L. -lft -lftprintf -o checker










#	gcc -Wall -Wextra -Werror main.c push_swap.c mini_sort.c mini_sort_2.c pre_sort.c pre_insort.c push_a.c push_b.c r_or_rr.c sort_stack.c atoli.c check_args.c cpy_stacks.c do_oper.c do_p.c do_r.c do_rr.c do_s.c init_a_b_stacks.c  -L. -lft -lftprintf





# 


# cpy_stacks.c

# 
# 
# 
# 


# insertion_sort.c
# mini_sort.c
# mini_sort_2.c
# pre_insort.c
# pre_sort.c
# 
# push_a.c
# push_b.c
# push_swap.c
# push_swap.h
# r_or_rr.c
# sort_stack.c