all:
	gcc -Wall -Wextra -Werror main.c push_swap.c do_p.c do_r.c do_rr.c do_s.c check_args.c mini_sort.c insertion_sort.c sort_stack.c init_a_b_stacks.c pre_sort.c mini_sort_2.c cpy_stacks.c pre_insort.c push_a.c push_b.c atoli.c print_stack.c r_or_rr.c -L. -lft -lftprintf -o push_swap









#	gcc -Wall -Wextra -Werror main.c push_swap.c mini_sort.c mini_sort_2.c pre_sort.c pre_insort.c push_a.c push_b.c r_or_rr.c sort_stack.c atoli.c check_args.c cpy_stacks.c do_oper.c do_p.c do_r.c do_rr.c do_s.c init_a_b_stacks.c  -L. -lft -lftprintf




# 

# checker
# 
# do_oper.c

# get_next_line.c



# 
# 
# 
# 
# 
# 
#
# 
